let tab0 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg', '/images/slider/test3.jpg');
followEvent('.infrastructure__button-left-roads', '.infrastructure__button-right-roads', '.infrastructure__slider-img-roads', tab0);
let tab1 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-light', '.infrastructure__button-right-light', '.infrastructure__slider-img-light', tab1);
let tab2 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-lighthouse', '.infrastructure__button-right-lighthouse', '.infrastructure__slider-img-lighthouse', tab2);
let tab3 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-fence', '.infrastructure__button-right-fence', '.infrastructure__slider-img-fence', tab3);
let tab4 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-area', '.infrastructure__button-right-area', '.infrastructure__slider-img-area', tab4);
let tab5 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-bench', '.infrastructure__button-right-bench', '.infrastructure__slider-img-bench', tab5);
let tab6 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-track', '.infrastructure__button-right-track', '.infrastructure__slider-img-track', tab6);
let tab7 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-playground', '.infrastructure__button-right-playground', '.infrastructure__slider-img-playground', tab7);
let tab8 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-sandbox', '.infrastructure__button-right-sandbox', '.infrastructure__slider-img-sandbox', tab8);
let tab9 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-group', '.infrastructure__button-right-group', '.infrastructure__slider-img-group', tab9);
let tab10 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-communication', '.infrastructure__button-right-communication', '.infrastructure__slider-img-communication', tab10);
let tab11 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-forest', '.infrastructure__button-right-forest', '.infrastructure__slider-img-forest', tab11);
let tab12 = takeAllImages('/images/slider/slider__img-item1.png', '/images/slider/test1.jpg', '/images/slider/test2.jpg');
followEvent('.infrastructure__button-left-land', '.infrastructure__button-right-land', '.infrastructure__slider-img-land', tab12);